services:
  - type: web
    name: number-plate-detector
    env: python
    pythonVersion: 3.11
    plan: free
    region: oregon
    buildCommand: CARGO_HOME=/tmp/cargo pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
